# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: true

- task: NodeTool@0
  inputs:
    versionSpec: 18.x
  displayName: 'Install Node.js'
- script: npm install
  displayName: 'npm install'
- script: npm run prebuild
  displayName: 'npm run prebuild'
- script: npm run build
  displayName: 'npm run build'

- task: EsrpCodeSigning@4
  displayName: ESRP CodeSigning Files
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: build
    Pattern: >-
      **/*.js

      !**/Tests/**
    UseMinimatch: true
    signConfigType: inlineSignParams
    CertificateId: 0
    inlineOperation: >-
      [
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: 20

- script: npm pack build/
  displayName: 'npm pack build - generate tarball file'

- task: CopyFiles@2
  displayName: 'Copy publish file to Artifact Staging Directory'
  inputs:
    SourceFolder: ./
    Contents: '*.tgz'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  name: PublishPipelineArtifact1
  displayName: 'Publish Artifact: Build Outputs'
  inputs:
    ArtifactName: BuildOutputs
    TargetPath: $(Build.ArtifactStagingDirectory)