// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/**
 * This example demonstrates Work Item Filters for Durable Task workers.
 *
 * Work Item Filters allow a worker to tell the sidecar which orchestrations,
 * activities, and entities it is configured to handle. The sidecar then only
 * dispatches matching work items to that worker, enabling efficient routing.
 *
 * Key concepts demonstrated:
 * - Auto-generated filters from the worker's registry (default behavior)
 * - Explicit filters via useWorkItemFilters()
 *
 * This example runs against:
 *   DTS Emulator:
 *     docker run --name dts-emulator -i -p 8080:8080 -d --rm mcr.microsoft.com/dts/dts-emulator:latest
 *   Then:
 *     npx ts-node --swc examples/work-item-filters/index.ts
 */

import {
  ActivityContext,
  OrchestrationContext,
  TOrchestrator,
  WorkItemFilters,
} from "@microsoft/durabletask-js";
import {
  DurableTaskAzureManagedClientBuilder,
  DurableTaskAzureManagedWorkerBuilder,
} from "@microsoft/durabletask-js-azuremanaged";

const endpoint = process.env.ENDPOINT || "localhost:8080";
const taskHub = process.env.TASKHUB || "default";

// ============================================================================
// Step 1: Define activities and orchestrators
// ============================================================================

const greet = async (_: ActivityContext, name: string): Promise<string> => {
  return `Hello, ${name}!`;
};

const add = async (_: ActivityContext, input: { a: number; b: number }): Promise<number> => {
  return input.a + input.b;
};

const greetingOrchestrator: TOrchestrator = async function* (
  ctx: OrchestrationContext,
  name: string,
): Promise<any> {
  const result = yield ctx.callActivity(greet, name);
  return result;
};

const mathOrchestrator: TOrchestrator = async function* (
  ctx: OrchestrationContext,
  input: { a: number; b: number },
): Promise<any> {
  const result = yield ctx.callActivity(add, input);
  return result;
};

// ============================================================================
// Step 2: Demonstrate different work item filter configurations
// ============================================================================

async function runWithAutoGeneratedFilters() {
  console.log("\n=== Scenario 1: Auto-Generated Filters (Default) ===");
  console.log("The worker auto-generates filters from its registered orchestrators and activities.");
  console.log("Only matching work items will be dispatched to this worker.\n");

  const client = new DurableTaskAzureManagedClientBuilder()
    .endpoint(endpoint, taskHub, null)
    .build();

  // No explicit filters — they are auto-generated from addOrchestrator/addActivity
  const worker = new DurableTaskAzureManagedWorkerBuilder()
    .endpoint(endpoint, taskHub, null)
    .addOrchestrator(greetingOrchestrator)
    .addActivity(greet)
    .build();

  await worker.start();
  console.log("Worker started with auto-generated filters for: greetingOrchestrator, greet");

  const id = await client.scheduleNewOrchestration(greetingOrchestrator, "Auto-Filters");
  console.log(`Scheduled orchestration: ${id}`);

  const state = await client.waitForOrchestrationCompletion(id, undefined, 30);
  console.log(`Result: ${state?.serializedOutput}`);

  await worker.stop();
  await client.stop();
}

async function runWithExplicitFilters() {
  console.log("\n=== Scenario 2: Explicit Filters ===");
  console.log("The worker uses explicitly provided filters instead of auto-generating them.");
  console.log("This is useful when you want fine-grained control over which work items to accept.\n");

  const client = new DurableTaskAzureManagedClientBuilder()
    .endpoint(endpoint, taskHub, null)
    .build();

  // Provide explicit filters — these override auto-generation
  const filters: WorkItemFilters = {
    orchestrations: [{ name: "mathOrchestrator" }],
    activities: [{ name: "add" }],
  };

  const worker = new DurableTaskAzureManagedWorkerBuilder()
    .endpoint(endpoint, taskHub, null)
    .addOrchestrator(mathOrchestrator)
    .addActivity(add)
    .useWorkItemFilters(filters)
    .build();

  await worker.start();
  console.log("Worker started with explicit filters for: mathOrchestrator, add");

  const id = await client.scheduleNewOrchestration(mathOrchestrator, { a: 17, b: 25 });
  console.log(`Scheduled orchestration: ${id}`);

  const state = await client.waitForOrchestrationCompletion(id, undefined, 30);
  console.log(`Result: ${state?.serializedOutput}`);

  await worker.stop();
  await client.stop();
}

// ============================================================================
// Step 3: Run all scenarios
// ============================================================================

(async () => {
  console.log(`Connecting to DTS emulator at ${endpoint}, taskHub: ${taskHub}`);

  try {
    await runWithAutoGeneratedFilters();
    await runWithExplicitFilters();

    console.log("\n=== All scenarios completed successfully! ===");
  } catch (error) {
    console.error("Error:", error);
    process.exit(1);
  }

  process.exit(0);
})();
