jobs:
    - job:
      templateContext:
          outputs:
              - output: pipelineArtifact
                path: $(Build.ArtifactStagingDirectory)
                artifact: drop
                sbomBuildDropPath: "$(System.DefaultWorkingDirectory)"
                sbomPackageName: "Durable Task JavaScript SBOM"
                # The list of components can't be determined from the webpacked file in the staging dir, so reference the original node_modules folder
                sbomBuildComponentPath: "$(Build.SourcesDirectory)/node_modules"
      steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
                versionSpec: 20.x
            displayName: "Install Node.js"
          
          # Install all workspace dependencies
          - script: npm ci
            displayName: "npm ci"
          
          # Build all packages (each workspace's build script runs its own prebuild)
          - script: npm run build
            displayName: "npm run build (all packages)"
          
          # Run tests for all packages
          - script: npm test
            displayName: "npm test (all packages)"
          
          # Prune dev dependencies so that only production dependencies are included in SBOM
          - script: npm prune --production
            displayName: "npm prune --production"
          
          # Pack @microsoft/durabletask-js
          - script: |
              cd packages/durabletask-js
              npm pack
            displayName: "pack @microsoft/durabletask-js"
          
          # Pack @microsoft/durabletask-js-azuremanaged
          - script: |
              cd packages/durabletask-js-azuremanaged
              npm pack
            displayName: "pack @microsoft/durabletask-js-azuremanaged"
          
          # Copy each package to its own staging subfolder
          - task: CopyFiles@2
            displayName: "Copy durabletask-js to staging"
            inputs:
                SourceFolder: $(System.DefaultWorkingDirectory)/packages/durabletask-js
                Contents: "*.tgz"
                TargetFolder: $(Build.ArtifactStagingDirectory)/buildoutputs/durabletask-js
          - task: CopyFiles@2
            displayName: "Copy durabletask-js-azuremanaged to staging"
            inputs:
                SourceFolder: $(System.DefaultWorkingDirectory)/packages/durabletask-js-azuremanaged
                Contents: "*.tgz"
                TargetFolder: $(Build.ArtifactStagingDirectory)/buildoutputs/durabletask-js-azuremanaged