jobs:
    - job:
      templateContext:
          outputs:
              - output: pipelineArtifact
                path: $(Build.ArtifactStagingDirectory)
                artifact: drop
                sbomBuildDropPath: "$(System.DefaultWorkingDirectory)"
                sbomPackageName: "Durable Task JavaScript SBOM"
                # The list of components can't be determined from the webpacked file in the staging dir, so reference the original node_modules folder
                sbomBuildComponentPath: "$(Build.SourcesDirectory)/node_modules"
      steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
                versionSpec: 20.x
            displayName: "Install Node.js"
          
          # Build main package
          - script: npm ci
            displayName: "npm ci"
          - script: npm run prebuild
            displayName: "npm run prebuild"
          - script: npm run build
            displayName: "npm run build"
          - script: npm prune --production
            displayName: "npm prune --production" # so that only production dependencies are included in SBOM
          - script: npm pack build/
            displayName: "pack npm package"
          
          # Build azure-managed extension package
          - script: |
              cd packages/durabletask-js-azuremanaged
              npm ci
              npm run build
              npm run test
              npm prune --production
            displayName: "Build azure-managed extension"
          - script: |
              cd packages/durabletask-js-azuremanaged
              npm pack
            displayName: "pack azure-managed extension"
          
          - task: CopyFiles@2
            displayName: "Copy package to staging"
            inputs:
                SourceFolder: $(System.DefaultWorkingDirectory)
                Contents: "*.tgz"
                TargetFolder: $(Build.ArtifactStagingDirectory)/buildoutputs
          - task: CopyFiles@2
            displayName: "Copy azure-managed extension to staging"
            inputs:
                SourceFolder: $(System.DefaultWorkingDirectory)/packages/durabletask-js-azuremanaged
                Contents: "*.tgz"
                TargetFolder: $(Build.ArtifactStagingDirectory)/buildoutputs