jobs:
    - job:
      templateContext:
          outputs:
              - output: pipelineArtifact
                path: $(Build.ArtifactStagingDirectory)
                artifact: drop
                sbomBuildDropPath: "$(System.DefaultWorkingDirectory)"
                sbomPackageName: "Durable Task JavaScript SBOM"
                # The list of components can't be determined from the webpacked file in the staging dir, so reference the original node_modules folder
                sbomBuildComponentPath: "$(Build.SourcesDirectory)/node_modules"
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: 20.x
            displayName: "Install Node.js"
          - script: npm ci
            displayName: "npm ci"
          - script: npm run-script build
            displayName: "npm run-script build"
          - script: npm prune --production
            displayName: "npm prune --production" # so that only production dependencies are included in SBOM
          - script: npm pack
            displayName: "pack npm package"
          - task: CopyFiles@2
            displayName: "Copy package to staging"
            inputs:
                SourceFolder: $(System.DefaultWorkingDirectory)
                Contents: "*.tgz"
                TargetFolder: $(Build.ArtifactStagingDirectory)