pr: none
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  pipelines:
  - pipeline: DurableTaskJSBuildPipeline
    source: durabletask-js.official
    branch: main

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux

    stages:
    - stage: release
      jobs:
      - job: durabletask_js
        displayName: 'Release @microsoft/durabletask-js'
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: DurableTaskJSBuildPipeline
            artifactName: drop
            targetPath: $(System.DefaultWorkingDirectory)/drop

        steps:
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@9
          displayName: 'ESRP Release @microsoft/durabletask-js'
          inputs:
            connectedservicename: 'dtfx-internal-esrp-prod'
            usemanagedidentity: true
            keyvaultname: 'durable-esrp-akv'
            signcertname: 'dts-esrp-cert'
            clientid: '0b3ed1a4-0727-4a50-b82a-02c2bd9dec89'
            folderlocation: '$(System.DefaultWorkingDirectory)/drop/buildoutputs/durabletask-js'
            owners: 'wangbill@microsoft.com'
            approvers: 'kaibocai@microsoft.com'
            mainpublisher: 'durabletask-js'

      - job: durabletask_js_azuremanaged
        displayName: 'Release @microsoft/durabletask-js-azuremanaged'
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: DurableTaskJSBuildPipeline
            artifactName: drop
            targetPath: $(System.DefaultWorkingDirectory)/drop

        steps:
        - task: SFP.release-tasks.custom-build-release-task.EsrpRelease@9
          displayName: 'ESRP Release @microsoft/durabletask-js-azuremanaged'
          inputs:
            connectedservicename: 'dtfx-internal-esrp-prod'
            usemanagedidentity: true
            keyvaultname: 'durable-esrp-akv'
            signcertname: 'dts-esrp-cert'
            clientid: '0b3ed1a4-0727-4a50-b82a-02c2bd9dec89'
            folderlocation: '$(System.DefaultWorkingDirectory)/drop/buildoutputs/durabletask-js-azuremanaged'
            owners: 'wangbill@microsoft.com'
            approvers: 'kaibocai@microsoft.com'
            mainpublisher: 'durabletask-js'
